### ISSUE TITLE
ScrollWindowEx

### ISSUE THREAD

**Issue by Miko321** [lmstearn/PrgLnch#10]
Hello, @lmstearn  i see you've not been much active in the forum, I'm writing about your topic on the forum [PicScroller].(https://www.autohotkey.com/boards/viewtopic.php?f=6&t=86418) 

I tried to study how you implemented the [ScrollWindowEx](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-scrollwindowex) function in your script, but i did not understand well how it works, I'm trying to achieve something similar:
[Scrollable GUI from given position](https://www.autohotkey.com/boards/viewtopic.php?f=76&t=93993&sid=1b9e7fbb016b3de15138c2144814fcfc)

If you could take a look at it, thank you!

**Comment by lmstearn** [comment]
Hi @Miko321,
PrgLnch doesn't scroll at all, you might be better off placing in issue in [ScrollCall](https://github.com/lmstearn/ScrollCall) instead. Although it's in C++, the PicScroller is mentioned in the [wiki,](https://github.com/lmstearn/ScrollCall/wiki) so that's fine. 😀
