### ISSUE TITLE
Prgs on Monitors: As per Configuration?

### ISSUE THREAD

**Issue by lmstearn** [lmstearn/PrgLnch#4]
On my "standard" two monitor setup, Prgs (bar some legacy and own monitor config) will mostly run on either monitor.
> When I tested it, it launched the programs on the second monitor (which is set as my primary) but said it was launching them on the first one while PrgLnch was on the second

@DS: You have three or four monitors? It sounds as if it's a continuation of the [issue of old](http://www.theassimilationlab.com/forums/topic/15816-prglnch-yet-another-game-launcher/?page=3&tab=comments#comment-445545) where Prgs would not launch on _any_ monitor bar the primary.
The first checkpoint is to determine if PrgLnch can change the resolution of any monitors bar the primary. Does changing the resolution of the primary monitor work as well? Download the [latest executable](https://github.com/lmstearn/PrgLnch/blob/master/PrgLnch.exe) and attempt to Change Res on the orange ones. Thanks.

**Comment by deathssoul** [comment]
Give me a bit, I've got a family member in the hospital and not doing well so it may be a few days before I can get to it.

**Comment by deathssoul** [comment]
Nope, changing the resolution in PrgLaunch doesn't seem to have any effect and things still run at 1920x1200 (the native resolution). Also, the resolution list lists 1920x1080 at 23 Hz instead of 60 Hz (but lists others at 60 Hz and some at 23 Hz) if that makes a difference.

**Comment by lmstearn** [comment]
Changing resolution on the primary doesn't work either? Presumably it works from Windows Settings, or do you prefer that through the AMD GUI (Edit: Radeon™ Software Adrenalin 2019 Edition 19.11.1. )
As a matter of interest, try these programs:
https://www.displayfusion.com/Download/?
http://dualmonitortool.sourceforge.net/download.html
Do they make any difference?

**Comment by deathssoul** [comment]
Changing it on the primary doesn't work either, unless I'm doing something wrong. I open up PrgLaunch, select the program from the drop down list, hit Config, and set the resolution. Then I hit test run program, correct?

I'm going on vacation again in a few days so I'll be a bit slow.

**Comment by lmstearn** [comment]
Don't even have to configure any programs, Just "Change Res" should be on the button when no Prg is selected. (Happens when running PrgLnch for the first time.)
Sure, that's fine. Vacation is a good choice after the Easter "rush". :P.
It may be a problem with how the co-ordinates are calculated, but rather not take that road until we have a second opinion, In other words, another program which can change the resolution of any monitor without issue.

**Comment by deathssoul** [comment]
That didn't seem to do anything. I tried 1920x1080, 1280x720, and 800x480 but the resolution didn't change. Which version of Windows are you using? It's possible they changed something in the API.

**Comment by lmstearn** [comment]
Using 1803, but need to get the Update ISO as WU keeps breaking.
Oops, sorry- it was a global variable that didn't want to go local.
"[Fixed](https://github.com/lmstearn/PrgLnch/blob/master/PrgLnch.exe)." Hope it makes a difference.

**Comment by deathssoul** [comment]
Okay, that fixed the resolution changing. However, now when I run it, it changes all open windows to the first monitor instead of the primary (even though I have display 2 selected) and doesn't switch them back to the second screen on close (it also does this for programs not even open).

Well, some of them. I suspect it does it for any for which the processes are still cached.

**Comment by lmstearn** [comment]
Alright, some questions:

- When running PrgLnch for the first time (without ini file) does it do anything to any windows of other running applications?
- Without launching any Prgs, does it change the resolution correctly for any monitor you select?
- Now make a shortcut for a small app that doesn't touch any monitor or its resolution (e.g.Notepad). Even though it's supposed to run on Display2, it launches on Display1, correct? But when it launches on Display1, are any other (non-related) applications placed there as well?
- If yes for the last question, then we have a problem. If no, but yes for the previous questions, then it's likely an issue with co-ordinates. (Best for this to be dealt with first before any other Prgs are configured)
Thanks

**Comment by deathssoul** [comment]
- Nope
- Yes
- No, the opposite: they only launch on Display2 even when Display1 or Display3 is selected

**Comment by lmstearn** [comment]
Posted an [update](https://github.com/lmstearn/PrgLnch/blob/master/PrgLnch.exe). Not sure it's going to solve, but if at least one Prg can launch in another monitor, it's a start!

**Comment by deathssoul** [comment]
Still no go: it still only launches on Display2 when the others are selected.

**Comment by lmstearn** [comment]
Thanks. Working on a way to debug this, stay tuned!

**Comment by lmstearn** [comment]
Try the attached. If PrgLnch is run from a shell object in a monitor other than the primary monitor, PrgLnch will relocate itself to the primary monitor. That's another thing to be fixed- and also the issue of user moving the PrgLnch GUI from monitor to monitor.
[PrgLnch.zip](https://github.com/lmstearn/PrgLnch/files/3165881/PrgLnch.zip)

**Comment by deathssoul** [comment]
Still only launching on the primary monitor even though one of the other ones is selected.

**Comment by lmstearn** [comment]
It's a worry. Try opening PrgLnch.ini with Notepad and keep it open in the default monitor, and consider the venerable WinPad. Download the original here:
https://autohotkey.com/board/topic/19990-windowpad-window-moving-tool/
Also consider the updated Hoppfrosch version, but sadly the following command didn't work here:
`<YourPathto>\WindowPad.exe "WindowScreenMove, P, PrgLnch.ini"`
The original worked. There's a html help file bundled in the zip- it gives more monitor options like N or monitor number.
If this doesn't work for any window moves or operations on other monitors, then it's possibly an issue with the gpu driver. Currently working on the (separate) issue of PrgLnch not launching on the monitor it was started on, if the startup monitor was not primary. Its success/failure on your setup may shed further clues.
Is it possible to get a screenshot of the virtual screen- a bit like what's in this thread:
https://stackoverflow.com/questions/55501266/determining-which-monitor-the-cursor-is-in-via-autohotkey-monitor-bottom-value
[ref](https://docs.microsoft.com/en-us/windows/desktop/gdi/the-virtual-screen). They also talk of moving the monitors around in it- is that possible on yours?

**Comment by deathssoul** [comment]
The monitor setting in the INI file is being properly changed but it's not taking effect (only displays on the primary). If we can change the resolution of the other monitors, we _should_ be able to launch on the other monitors. It may be a limitation with AHK, though. What about passing the launching mechanism through a DLL and doing it that way? The external code need only be a few lines (it would just take the program name, path, and monitor to launch on) and may be the best way of handling it.

What do you want me to do? I'm not understanding.

**Comment by lmstearn** [comment]
Try [this iteration](https://github.com/lmstearn/PrgLnch/blob/master/PrgLnch.exe)- but with a new variation. Move the containing folder or shortcut to the file to another monitor, and launch it from there. The GUI should load on that monitor as opposed to what we all getting used to as the form shifting back onto the primary monitor.

**Comment by deathssoul** [comment]
The new version gives a trojan warning from MSE and won't let me mess with it, the previous ones were fine and didn't provide the warning (I just scanned the previous archive to check and it still came out clean).

**Comment by lmstearn** [comment]
Really? But the last stable release of MSE was in 2016. Does the latest W10 allow you to run it?
No problem with Defender here- is it possible to verify that on yours? It's the same version of AHK- can it compile the script on your machine? There's a [thread on false positives](https://www.autohotkey.com/boards/viewtopic.php?f=17&t=62266&sid=5192d0017cd97c90cd69230fbc606cf6) at AHK.
Here's the [VirusTotal report](https://www.virustotal.com/gui/file/9db76a63f4696f155f50de8e4e6ef3046ab8eddc58e8ef8097d9c333834023c2/detection) for the latest iteration- Googling reveals the detections are false positives.
Try the [following](https://github.com/lmstearn/PrgLnch/blob/master/PrgLnch.exe) from another monitor. Thanks.

**Comment by deathssoul** [comment]
Sorry, Windows Defender. I'm still calling it MSE as it's easier to abbreviate that way.

Same thing: that new one is being blocked from being downloaded.

**Comment by lmstearn** [comment]
You can always add it to the [exclusion list.](https://support.microsoft.com/en-au/help/4028485/windows-10-add-an-exclusion-to-windows-security). Alternatively, here's a zipped copy to be trialed from monitor 1 or 3: [PrgLnch.zip](https://github.com/lmstearn/PrgLnch/files/3200974/PrgLnch.zip). Let's hope it works for the imminent release. :runner:

**Comment by deathssoul** [comment]
Moving the containing directory to a different monitor and launching it didn't help: it still ran the shortcut on the primary monitor (PrgLaunch correctly launched on the other monitor however).

**Comment by lmstearn** [comment]
Here's a build that outputs to _Dbg_Out.txt_ in the script directory. [PrgLnch.zip](https://github.com/lmstearn/PrgLnch/files/3207348/PrgLnch.zip). Please post it along with _PrgLnch.ini_ as an attachment after running a Prg in the same monitor and another, as well as the following consideration:
If PrgLnch is started on monitor 1, and the prg is set to run on monitor 1, it launches on 2? And if PrgLnch is started on monitor 3, and the prg is set to run on monitor 3, it again launches on 2?
Also, when the monitors are [detected in Settings,](https://support.microsoft.com/en-au/help/4340331/windows-10-set-up-dual-monitors) do the monitor ID numbers appear on the appropriate displays?

**Comment by deathssoul** [comment]
First one is PrgLaunch on monitor 2, launch program on same. Second is on monitor 2, launch set to monitor 1. Third is on 1, launch set to 1.
[Dbg_Out.txt](https://github.com/lmstearn/PrgLnch/files/3216167/Dbg_Out.txt)
[Dbg_Out.txt](https://github.com/lmstearn/PrgLnch/files/3216155/Dbg_Out.txt)
[Dbg_Out.txt](https://github.com/lmstearn/PrgLnch/files/3216158/Dbg_Out.txt)

[PrgLnch.zip](https://github.com/lmstearn/PrgLnch/files/3216162/PrgLnch.zip)

Correct, Windows Settings shows the proper IDs.
In all cases, program launches on primary (2) no matter what it's set to launch on or which monitor PrgLaunch is launched from.

**Comment by lmstearn** [comment]
Thanks. [MyReels ](https://github.com/lmstearn/MyReels/issues/4#issuecomment-458115448) only recognizes screen resolutions on the "DPI Aware" primary monitor, and all its internal resizing and scaling is based on that. There would have to be a fair bit of code added for it to recognize a multi-monitor environment and be [per monitor DPI Aware](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=37913&p=277998#p277998). It won't move to the second monitor on this setup either- well- it actually does move the first form - the splash screen - for a brief moment, but the second (main) form knows nothing about the first form and loads onto the primary monitor as usual. As do all the other forms in succession.
Also, a sloppy mistake here- there's also _Dbg_Out.txt_ in your MyReels Directory which can posted here & canned.
Sorry about the confusion. Any better luck with Notepad on other monitors? Try this no_debug [PrgLnch.zip](https://github.com/lmstearn/PrgLnch/files/3219423/PrgLnch.zip)
If that fails, we'll be looking at [driver functions](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/ccd-apis). :sweat_smile:

**Comment by deathssoul** [comment]
I think I should wait until the next Windows update rolls out for me. I noticed the other day when I was trying to install The Sims 4 that things were still wonky (the 2010 version of the C runtime wouldn't install even though the 2013 one had no issues) so I think it wouldn't be a bad idea to see if the next update fixes some of this. The October update has been causing me all sorts of issues. :/

**Comment by lmstearn** [comment]
Fair enough- it looks like it should work for you in any case. 2.0 is being released!

**Comment by lmstearn** [comment]
From discussion at MS Teams:
> No luck but I think I know what's going on. Instead of moving the window, the code is moving the monitor numbers instead. So the center screen becomes 3 if I select three in the display list instead of the window moving to 3.

Strange action from the driver- it's beyond Prglnch code to modify it- re-opening just in case the issue is replicated elsewhere.

**Comment by lmstearn** [comment]
Closing as addressed by implementing [Splashy](https://github.com/lmstearn/Splashy/wiki) screens for monitor ID in version 2.3.
