### ISSUE TITLE
Initialise Lnch Pad Slots for Games

### ISSUE THREAD

**Issue by lmstearn** [lmstearn/PrgLnch#5]
Idea is to run a separate script to search the user's machine for executables associated with a game, and initialise the Lnch Pad with Prgs and Batches for various tasks associated with modding the game. Each of the six presets associated with some type of task associated with modding or running Oblivion. At this stage, TES games are a likely start.
An example would be renaming an ENB d3d9.dll in order to run the Oblivion Construction Set.
Another would be programs editing various texture or nif files, batched for convenience.
Easiest way is to start with a templated list of Prgs- e.g. if the user has Gimp instead of Blender, launch that instead.

**Comment by deathssoul** [comment]
Another option is to limply list the paths and program names in a file separated by newlines and populate them that way. Though, the presentation may be a bit messy with AHK.

**Comment by lmstearn** [comment]
Actually, the plan is to devise a cool looking GUI for the various games, so to allay the effect of the crappy PrgLnch GUI somewhat. :stuck_out_tongue:
Currently doing some tests regarding form transparency, it might be a while before getting a build up.
Although compiling a list of task and recommended Oblivion related executables is a good place to start. Have you any in mind?

**Comment by deathssoul** [comment]
What I had in mind was a dynamically generated list sourced from a text file.

I'm more of a programmer than a modder but a good starting point would be the official tools and the various Edit forms (probably best to use the command-line options so one doesn't need to worry about the silly Edit renaming stuff). Possibly Blender as well.

**Comment by lmstearn** [comment]
Here's a skeletal draft of what it's going to look like:
![LnchPadInit](https://user-images.githubusercontent.com/7629854/65389419-64a85900-dd99-11e9-94a0-420af086c581.JPG)

Here's the exe:
[LnchPadInit.zip](https://github.com/lmstearn/PrgLnch/files/3639844/LnchPadInit.zip)

A few points

- The first button will select items in the listbox that are installed on the target machine.
- The second button adds the selected items to the Lnch Pad slot, overwriting existing entries in the slot.
- (Urgent) A right or double click on a listbox item will bring up a popup help reference. It's easy just to include the item info in the current chm (HTML help), but looks and feels a bit cumbersome on a listbox. The other option is to have small popup windows as coded html or the like. What do you think?
- There is the choice of either including this script into PrgLnch itself, or running as a separate process. My preference is to bundle it in to PrgLnch, but there will still be issues of what is to be done viz hotkeys or controls to invoke the module as per req..

Edit: [Buddah](https://ortham.github.io/buddah/) makes it a lot easier. :smiley:
The [Blender NIF Plugin](https://github.com/niftools/blender_nif_plugin) has an installable exe, but the addon itself is not (verify). Not sure whether to include a ref to Blender itself or it via plugin. Bit of a rats' nest when we assume that because one has both Blender.exe and Skyrim, they have the plugin.

**Comment by deathssoul** [comment]
I would recommend moving the two buttons to the bottom and putting them side by side and moving the list boxes side by side above them.

Tooltips would likely be the better option for help stuff.

Either separate or bundled would make sense to me, up to you. :)

As for Blender: I would suggest, if possible, to include an identifier if the NIF Plugin is installed as it's not necessarily shipped with Blender itself.

**Comment by lmstearn** [comment]
That was considered earlier, but now not possible because only one Listbox per tab is allocated. Having the Listbox in the middle covering the game avatar isn't going to be a very complimentary look. Further, as will be demonstrated in the iteration attached, there will be a "popup" list of drives going down on the form which is activated by the search button. This will be handy for the user if he knows what drive his stuff is on, and negates the need of searching through backup and system volumes. The buttons and listbox for each game will go better with a different set of colours for the background and text. Do you have any suggestions?

Sadly, jump links cannot be implemented in standard tooltips. The idea of linking back to the mod's home page works when the modder sees a mod he doesn't know about, and after navigation to the home page can see why it was included in the "primary" list. Unfortunately, that brings in the scent of personal preference, one way around that is to set up a secondary mod list for each game.

Re Blender, noted. For the time being, it can be kept aside for a secondary list.

Here's the [updated build](https://github.com/lmstearn/PrgLnch/files/3802756/LnchPadInit.zip) with more friendly colours.

**Comment by lmstearn** [comment]
Completed! Details for Fallout to be added.
